services:
  - type: web
    name: medical-report-api
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-hin tesseract-ocr-kan &&
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false           # you'll paste the value manually on Render dashboard
      - key: FRONTEND_URL
        sync: false           # you'll paste your Vercel URL after deploying frontend
    rootDir: backend
